# Generated by Django 4.2.7 on 2024-01-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fihirana", "0010_alter_list_fihirana_ajout_titre"),
    ]

    operations = [
        migrations.AddField(
            model_name="fhrn_ajout",
            name="Mpihira",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
